packages:
  - '!**/dist/**'
  - 'packages/*'
  - 'packages/bridge/*'
  - 'packages/enhance'
  - 'apps/runtime-demo/*'
  - 'apps/modernjs-ssr/*'
  - 'apps/modernjs-ssr-data-loader/*'
  - 'apps/router-demo/*'
  - 'apps/manifest-demo/*'
  - 'apps/esbuild'
  - 'apps/*'
  - 'webpack'
  - 'assemble-release-plan'
  - 'packages/modernjs/__tests__/*'
